
package com.giophub.soap.jaxws.client.stub;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapServiceImplService", targetNamespace = "http://service.jaxws.soap.giophub.com/", wsdlLocation = "http://localhost:8081/JaxWsSoapService?wsdl")
public class SoapServiceImplService
    extends Service
{

    private final static URL SOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SOAPSERVICEIMPLSERVICE_QNAME = new QName("http://service.jaxws.soap.giophub.com/", "SoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/JaxWsSoapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SoapServiceImplService() {
        super(__getWsdlLocation(), SOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "SoapServiceImplPort")
    public SoapService getSoapServiceImplPort() {
        return super.getPort(new QName("http://service.jaxws.soap.giophub.com/", "SoapServiceImplPort"), SoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapService
     */
    @WebEndpoint(name = "SoapServiceImplPort")
    public SoapService getSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.soap.giophub.com/", "SoapServiceImplPort"), SoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
