
package com.giophub.soap.jaxws.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://contract.service.jaxws.soap.giophub.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://contract.service.jaxws.soap.giophub.com/", className = "com.giophub.soap.jaxws.client.stub.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://contract.service.jaxws.soap.giophub.com/", className = "com.giophub.soap.jaxws.client.stub.SayHelloResponse")
    @Action(input = "http://contract.service.jaxws.soap.giophub.com/SoapService/sayHelloRequest", output = "http://contract.service.jaxws.soap.giophub.com/SoapService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://contract.service.jaxws.soap.giophub.com/", className = "com.giophub.soap.jaxws.client.stub.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://contract.service.jaxws.soap.giophub.com/", className = "com.giophub.soap.jaxws.client.stub.HelloWorldResponse")
    @Action(input = "http://contract.service.jaxws.soap.giophub.com/SoapService/HelloWorldRequest", output = "http://contract.service.jaxws.soap.giophub.com/SoapService/HelloWorldResponse")
    public String helloWorld();

}
